version: v1.0.0
random_seed: 100

data_root: data

train_dataset: brats-met
test_datasets: [brats-met]

mod: t2w

epoch: 200
batch_size: 6

distance_per_slice: 5

learning_rate: 3e-5
weight_decay: 5e-2
warmup_steps: 20
total_steps: 25000

print_freq_step: 5
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [12,18,24]

anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25

prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results

prompts:
  normal: [
    normal,
    healthy,
    negative,
    unremarkable,
    clear,
    asymptomatic,
    normal findings,
    no findings,
    in good health,
    no evidence of disease
  ]

  abnormal: [
        abnormal,
        positive,
        symptomatic,
        disease,
        lesion,
        pathological,
        impaired,
        evidence of disease,
        abnormal finding,
        pathological condition,
        pathological abnormality
  ]